### PR TITLE
Change module naming to fit go-gorm repo

### PR DESCRIPTION
**Pull request by guypeled76**
- [v] Do only one thing
- [v] Non breaking API changes
- [v] Tested

### What did this pull request do?
Change the module naming to fit the go-gorm bigquery repository

### User Case Description
Module name should match repository by default

### CODE REVIEW

**Comment by guypeled76** [comment]
@jinzhu 
Do you want to give me write permissions to this repo so I can merge changes?
Or do you want to manage it?

10x,
Guy

**Comment by jinzhu** [comment]
Hello @guypeled76 

Sorry for the delay, just assigned the manage permission to you.

Thank you for your contribution!

**Comment by guypeled76** [comment]
Thanks,
Guy

**Comment by jinzhu** [comment]
> Thanks,
> Guy

Hello @guypeled76 

Thank you for your contribution, so the BigQuery is usable now?

**Comment by guypeled76** [comment]
Hi @jinzhu 

The things that are in the test coverage are usable.
We are just starting to move to it so it is not yet battle tested but it looks good.

So it's usable but in an early stage.
Every time we will find an issue or require another bigquery feature we will add it to the test coverage as well. It seems that all the "regular" GORM API like Where, Find, Not and so on are working out of the box. We only needed to add support for the nested tables/rows both in creation and when querying. We didn't use JOINS as we don't need it but we might use it in the near future for joining a small table with a larger one.

Hope that makes sense.
Guy

**Pull request merged**
